# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run task test
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
