services:
  app_db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - app_network


  fastapi_app:
    image: fastapi-do-zero
    entrypoint: ./scripts/entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - app_db
    env_file:
      - .env
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
